CC = gcc

test_samples: test_samples.c samples.c ../../proto/base.c
	$(CC) -o test_samples test_samples.c samples.c ../../proto/base.c

test: test.c samples.c ../../proto/base.c
	$(CC) -o test test.c samples.c ../../proto/base.c
